### ISSUE TITLE
CI npm release

### ISSUE THREAD

**Issue by jgroom33** [eykrehbein/strest#106]
This guide seems good:

https://blog.travis-ci.com/2018-04-11-how_to_publish_node_js_packages_with_travis_ci_and_packagecloud/

**Comment by eykrehbein** [comment]
working on a solution 👍

**Comment by eykrehbein** [comment]
#107 
Also added guidelines in [CONTRIBUTING.md](https://github.com/eykrehbein/strest/blob/master/CONTRIBUTING.md)
