### ISSUE TITLE
Stress testing ?

### ISSUE THREAD

**Issue by vinyguedess** [eykrehbein/strest#11]
Why don't add a possibility for stress testing permiting tests writer define how much requests per second wants to simulate ?

**Comment by eykhagen** [comment]
Love this idea!

**Comment by vinyguedess** [comment]
How can I contribute ?

**Comment by eykhagen** [comment]
@vinyguedess You can fork this repo and create a pull request with your changes

**Comment by eykhagen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Stress testing](https://trello.com/c/Y6R6IETs/9-stress-testing)

**Comment by Spengreb** [comment]
Working on this at the moment. 

The basic idea is to add 'repeat' and 'threads' into the schema of a request to start with. Firing requests off as quickly as possible and concurrently. Each thread being a user effectively. Though would like this configurable in future with a "ramp-up period" similar to JMeter. 

As a side-effect with the repeat function would it be possible to use Faker in the URL too? i.e. repeat request but each time have a bit of Fake or random data in the URL.

Will post a PR when I've got it working, at the moment I only have schema validation done. 

Anything you dont agree with let me know!

**Comment by eykhagen** [comment]
@Spengreb thanks for contributing! As I said on Twitter, I'm unfortunately unable to work on the project atm so every help is even more appreciated! :D 

Your idea sounds good! And to answer your question: you can use the Faker keyword everywhere just like the Value keyword since regex searches every key of each request for those patterns

**Comment by eykrehbein** [comment]
Added a feature to repeat a request x amount of times in #35. It's not per second but synchronously. Do you think a per-second-stress-test is still in need? @vinyguedess

**Comment by vinyguedess** [comment]
No, the purpose is check for concorrent connections. I think it satisfies it.
