### ISSUE TITLE
More MimeTypes

### ISSUE THREAD

**Issue by Beutlin** [eykrehbein/strest#129]
Is there any reason, why mimeType is validated againstthese two values ['application/json', 'text/plain']?

This is a limitation of the flexibility. I need also  at least those types:
- text/xml
- application/xml
- application/x-www-form-urlencoded

The attribute "text" is enough for me. I can paste the correct body payload on my own into the text attribute.
Thus solutions handling formData is not necessary for me.

Please either remove the validation mimeType or add the most common types into the validation list.

**Comment by bradrhodes** [comment]
I have the same problem and @Beutlin 's solution would also be fine for me.
