### ISSUE TITLE
Install fails because of jsonpath postinstall

### ISSUE THREAD

**Issue by lonix1** [eykrehbein/strest#133]
I install using `sudo npm i -g @strest/cli`

During postinstall it shows:

> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! jsonpath@1.0.0 postinstall: `node lib/aesprim.js > generated/aesprim-browser.js`
> npm ERR! Exit status 2
> npm ERR! 
> npm ERR! Failed at the jsonpath@1.0.0 postinstall script.

**Comment by jgroom33** [comment]
https://github.com/artilleryio/artillery/issues/548

**Comment by lonix1** [comment]
@jgroom33 Thanks.

`npm --ignore-scripts` is a hack, but it does allow me to install... I wonder why it doesn't work?

Anyways, now I can run a strest file from the shell.

But I can't run from the vscode plugin - I get an error popup with `Could not calculate YAML path`.

**Comment by jgroom33** [comment]
the plugin depends on where your cursor is.  it needs to be within a request object

**Comment by jgroom33** [comment]
i agree the install is a hack. `yarn` seems to work better

**Comment by lonix1** [comment]
Doesn't work for me... even if the cursor is within the request text. Also when I click the blue button on the top-right. In both cases I get that popup.

**Comment by jgroom33** [comment]
What OS and versions of the libs?

**Comment by lonix1** [comment]
latest of everything:
ubuntu 18.10
strest 2.4.0
stREST Client 0.1.1
vscode 1.31.0

**Comment by jgroom33** [comment]
since this is an issue with the plugin, it should be opened there: https://github.com/jgroom33/vscode-strest-client/issues
closing this in favor of the hack unless a better approach is suggested
