### ISSUE TITLE
CodeClimate integration

### ISSUE THREAD

**Issue by vinyguedess** [eykrehbein/strest#144]
Have you considered integrate with a service that can check for code quality and tests coverage ?
I really appreciate and recommend [CodeClimate](https://codeclimate.com).
I was looking for some parts of the [code](https://github.com/eykrehbein/strest/blob/master/src/test.ts) and there're some huge functions that could be splitted into smaller ones, making code more readable for example.

**Comment by eykrehbein** [comment]
Not considered it yet, but it seems really interesting - thank you. Also thinking about a complete rewrite of the framework

**Comment by jgroom33** [comment]
If you're considering a rewrite, check out these two for inspiration:
ansible
postwoman

**Comment by vinyguedess** [comment]
@eykrehbein I'd love help on it. There's a roadmap or it's a lonely job ?
