### ISSUE TITLE
feature suggestion: derive yaml from an OpenAPI spec

### ISSUE THREAD

**Issue by emckean** [eykrehbein/strest#18]
it looks like a lot of the YAML needed overlaps with what's in an OpenAPI spec, do you have plans for a converter or just using the OpenAPI spec directly?

**Comment by eykhagen** [comment]
Hi @emckean. What do you exactly mean by that?

**Comment by emckean** [comment]
so OAI (formerly known as Swagger) looks like this:
```
paths:
  /user/{userId}:
    get:
      summary: Returns a user by ID.
      parameters:
        - name: userId
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type : integer
            format: int64
            minimum: 1
      responses: 
        '200':
          description: OK
```
so you can see that you can get 'method' , 'data:params', and so on out of the OAI spec. (You can also get 'url' from a different section.)

**Comment by emckean** [comment]
more info [here](https://github.com/OAI/OpenAPI-Specification)!

**Comment by lastlegion** [comment]
In favor of using the OpenAPI spec 👍

**Comment by jgroom33** [comment]
is the design goal to import from a OAI spec (i.e. create a templated strest.yml) or to use that spec in place of the existing schema?

**Comment by eykrehbein** [comment]
The OAI spec schema doesn't make that much sense for me neither

**Comment by jgroom33** [comment]
I recommend closing this.  It should be implemented as a codegen function of swagger-codegen:
https://github.com/swagger-api/swagger-codegen

**Comment by jgroom33** [comment]
Maybe this could be easily modified to provide this function: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwaggerYamlGenerator.java
