### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by jgroom33** [eykrehbein/strest#39]
installing node/npm can be avoided for those using Docker

**Comment by eykrehbein** [comment]
Good idea. I'm not that confident in using Docker so any help would be very appreciated.

**Comment by jgroom33** [comment]
PR #45

**Comment by jgroom33** [comment]
You can set up some hooks to build automatically and publish on dockerhub.  Then people wouldn't need to build the image themselves.
https://docs.docker.com/docker-hub/builds/#create-an-automated-build

**Comment by jgroom33** [comment]
Resolved with #45
