### ISSUE TITLE
Allow log: Env(LOG_STREST)

### ISSUE THREAD

**Issue by jgroom33** [eykrehbein/strest#49]
This would be good to support global logging on/off
log: Env(LOG_STREST)

^ fails schema

**Comment by eykrehbein** [comment]
What do you mean by that exactly?

**Comment by adiman9** [comment]
I believe what is meant is that `log` currently only accepts a boolean in the schema and it has to be set manually per request in the yaml. It would be good if we could use the `Env()` operator to use an environment variable to globally turn on / off logging for all requests without having to change the yaml.

**Comment by eykrehbein** [comment]
It was basically already integrated but I forgot that the Joi pattern blocked the use of a string. But this was fixed for the log param in #53 👍
