### ISSUE TITLE
Reusable tests

### ISSUE THREAD

**Issue by andreoav** [eykrehbein/strest#60]
I think it is a good idea to be able to extract repeatable tests in dedicated files and import them.

Ex: I want to modularize some tests by domain, and each domain needs to have an initial authentication request that is common to all tests.

**Comment by jgroom33** [comment]
This seems possible in the existing chaining behavior. Can you describe the use case in greater detail?

**Comment by andreoav** [comment]
I want to create 2 test suites, one for each specific business domain.
Each suite depends on an authentication token.

I don't want to copy and paste the login request in each suite, so I ask if there is a way to `require` the login request that is saved in another file.

**Comment by jgroom33** [comment]
So you want to do this:

```
version: 1
require: ../login.strest.yml
...
```

It's currently possible to execute tests on a directory. So this implementation could potentially exit the directory and run a set of tests.

Are there other use cases?

**Comment by jgroom33** [comment]
#86 is another implementation option
