### ISSUE TITLE
Schema validation fails silently

### ISSUE THREAD

**Issue by finestructure** [eykrehbein/strest#97]
**Describe the bug**
I've written a request that fails schema validation but the strest run does not fail.

**To Reproduce**
- create a request yml that is invalid
- run it
- the run passes

**Expected behavior**
- the run should fail with a non-zero exit code

**Additional context**

```
[ Strest ] Found 3 test file(s)
[ Strest ] Schema validation: 2 of 3 file(s) passed

Executing tests in ./
Executing tests in: /app/tests/
Executing tests in: /app/tests/tokens/
✔ Testing userToken succeeded (0.573s)

[ Strest ] ✨  Done in 0.634s
```

The only indication that something went wrong is `2 of 3 file(s) passed` at the top, which is easy to miss, especially in longer scripts.

**Comment by jgroom33** [comment]
Agreed. It should also show details of the failure.

**Comment by finestructure** [comment]
I've also just come across this one here, which is very similar and doesn't error out (although it's more obvious):

```
✔ Testing create_contract_1 succeeded (0s)

Status: undefined
Status Text: undefined

Headers:

undefined

Data:

undefined

✔ Testing create_contract_2 succeeded (0s)
```

I'm referencing a `Value(...)` that doesn't exist because I didn't run all the necessary tests in the batch.

**Comment by jgroom33** [comment]
That should probably be a new issue. Add an example yaml that is expected to pass but doesn't

**Comment by finestructure** [comment]
Ok, I've added https://github.com/eykrehbein/strest/issues/99

And thanks for your swift reply. I'd take a look into this myself but JS is not my forte :)

**Comment by jgroom33** [comment]
Check out
CONTRIBUTING.md
This is the line that does the validation:
https://github.com/eykrehbein/strest/blob/master/src/yaml-parse.ts#L40
